###

GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
   "nombre_cine": "Supercines",
  "Direccion":  "Av Simon Bolivar ",
  "nombre Administrador":  "Carlos Sanchez",
  "TelefonoContacto":  "096542351" ,
   "hora_Apertura": "08:00-20:00"

}

###
DELETE http://localhost:9000/api/4 HTTP/1.1

###
PUT http://localhost:9000/api/6 HTTP/1.1
Content-Type: application/json

{
  "nombre_cine": "MULTICINES CENTRO",
  "Direccion":  "Av Moran Valverde ",
  "nombre Administrador":  "Enrique Garzon",
  "TelefonoContacto":  "096542351" ,
  "hora_Apertura": "08:00-20:00"

}


//mostrar peliculas
###

GET http://localhost:9000/api_peliculas HTTP/1.1

###
// crear peliculas
POST http://localhost:9000/api_peliculas HTTP/1.1
Content-Type: application/json

{
  "id": "7",
  "nombrePelicula":  "THOR ",
  "Categoria":  "Ficcion",
  "Esta_en_Cartelera":  "SI" ,
  "restriccion": "+1",
  "fecha_estreno": "14/12/2021"

}

###
//actualizar peliculas
PUT http://localhost:9000/api_peliculas/4 HTTP/1.1
Content-Type: application/json

{
  "id": "7",
  "nombrePelicula": " THOR ",
  "Categoria":  "Ficcion",
  "Esta_en_Cartelera": "NO" ,
  "restriccion": "+15",
  "fecha_estreno": "11/12/2020"
}

###
// eliminar pelicula
DELETE http://localhost:9000/api_peliculas/4 HTTP/1.1

###
//consultar peliculas registraa por cine
GET http://localhost:9000/api_peliculas_cine HTTP/1.1

